context:
  name: html2markdown
  version: "2.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/JohannesKaufmann/html-to-markdown/archive/refs/tags/v${{ version }}.tar.gz
  sha256: da15e96199bea9ed610996548f43eae19059edc364ac08baf107c0777fefbea5

build:
  number: 0
  script: build.sh

requirements:
  build:
    - go

tests:
  - script:
      - html2markdown --version
      - echo "<strong>important</strong>" | html2markdown | grep -q "\\*\\*important\\*\\*"

about:
  homepage: https://html-to-markdown.com
  license: MIT
  license_file: LICENSE
  summary: Convert HTML to Markdown
  description: |
    Convert HTML to Markdown. Even works with entire websites and
    can convert HTML from URLs, files, or stdin.
  repository: https://github.com/JohannesKaufmann/html-to-markdown

extra:
  recipe-maintainers:
    - jwintz
